#
## Cookbook Name:: hc_tomcat
## Attributes:: default
##
## Copyright 2010-2015, company, Inc.
##

default['hc_tomcat']['databag_name'] = 'artifact_cred'
default['hc_tomcat']['databag_id'] = 'artifact_cred'
default['hc_tomcat']['remove_dirs'] = ['docs','examples','host-manager', 'manager']
default['hc_tomcat']['base_version'] = '8'
if node['hc_tomcat']['base_version'] == '7'
  default['package_url'] = 'http://artifactory.demo.company.com/artifactory/chef-repo/tomcat/apache-tomcat-7.0.55.tar.gz'
  default['hc_tomcat']['package_name'] = 'apache-tomcat-7.0.55.tar.gz'
  default['hc_tomcat']['tomcat_dir_name'] = 'apache-tomcat-7.0.55'
  default['hc_tomcat']['zip_path'] = '/opt/tomcat7.zip'
else node['hc_tomcat']['base_version']  == '8'
  default['package_url'] = 'http://artifactory.demo.company.com/artifactory/chef-repo/apache-tomcat-8.0.30.tar.gz'
  default['hc_tomcat']['package_name'] = 'apache-tomcat-8.0.30.tar.gz'
  default['hc_tomcat']['tomcat_dir_name'] = 'apache-tomcat-8.0.30'
  default['hc_tomcat']['zip_path'] = '/opt/tomcat8.zip'
end

#default['hc_tomcat']['package_name'] = 'Aapache-tomcat-8.0.30.tar.gz'
#default['hc_tomcat']['package_url'] = 'http://artifactory.demo.company.com/artifactory/webapp/browserepo.html?pathId=chef-repo%3Aapache-tomcat-8.0.30.tar.gz'
default['hc_tomcat']['install_path'] = '/usr/local'
default['hc_tomcat']['symlink'] = 'tomcat'
default['hc_tomcat']['tomcat_home'] = "#{node['hc_tomcat']['install_path']}/#{node['hc_tomcat']['tomcat_dir_name']}"
default['hc_tomcat']['bin_path'] = "#{node['hc_tomcat']['tomcat_home']}/bin"
default['hc_tomcat']['tomcat_user'] = 'tomcat'
default['hc_tomcat']['tomcat_group'] = 'tomcat'
default['hc_tomcat']['admin_user'] = 'admin'
default['hc_tomcat']['base_instance'] = "tomcat#{node['hc_tomcat']['base_version']}"
default['hc_tomcat']['port'] = 8080
default['hc_tomcat']['proxy_port'] = 443
default['hc_tomcat']['proxyname'] = ''
default['hc_tomcat']['secure'] = true
default['hc_tomcat']['scheme'] = 'https'
default['hc_tomcat']['max_connections'] = 1500
default['hc_tomcat']['keep_alive_timeout'] = 5000
default['hc_tomcat']['connection_timeout'] = 10000
default['hc_tomcat']['ssl_port'] = 8443
default['hc_tomcat']['ssl_proxy_port'] = nil
default['hc_tomcat']['ajp_port'] = 8009
default['hc_tomcat']['ajp_redirect_port'] = nil
default['hc_tomcat']['shutdown_port'] = 8005
default['hc_tomcat']['catalina_options'] = ''
default['hc_tomcat']['xmsx_percentage'] = '60'
#server.xml properties
default['hc_tomcat']['proxyname'] = ''

#default['hc_tomcat']['xmsx'] = ''
if node[:hc_tomcat].attribute?(:xmsx)  
  default['hc_tomcat']['java_options'] = "-Xms#{node['hc_tomcat']['xmsx']}M -Xmx#{node['hc_tomcat']['xmsx']}M "
else
  default['hc_tomcat']['xmsx'] = (node['memory']['total'][0..-3].to_f / 1024) * (node['hc_tomcat']['xmsx_percentage'].to_f / 100)
  default['hc_tomcat']['java_options'] = "-Xms#{node['hc_tomcat']['xmsx'].to_i}M -Xmx#{node['hc_tomcat']['xmsx'].to_i}M "
end
default['hc_tomcat']['use_security_manager'] = false
default['hc_tomcat']['authbind'] = 'no'
default['hc_tomcat']['deploy_manager_apps'] = true
default['hc_tomcat']['max_threads'] = 600
default['hc_tomcat']['ssl_max_threads'] = 150
default['hc_tomcat']['ssl_cert_file'] = nil
default['hc_tomcat']['ssl_key_file'] = nil
default['hc_tomcat']['ssl_chain_files'] = []
default['hc_tomcat']['ssl_enabled_protocols'] = nil
default['hc_tomcat']['ciphers'] = nil
default['hc_tomcat']['keystore_file'] = 'keystore.jks'
default['hc_tomcat']['keystore_type'] = 'jks'
# The keystore and truststore passwords will be generated by the
# # openssl cookbook's secure_password method in the recipe if they are
# # not otherwise set. Do not hardcode passwords in the cookbook.
 default['hc_tomcat']['keystore_password'] = 'company123'
 default['hc_tomcat']['truststore_password'] = 'company123'
#
default['hc_tomcat']['truststore_file'] = nil
default['hc_tomcat']['truststore_type'] = 'jks'
default['hc_tomcat']['certificate_dn'] = 'cn=localhost'
default['hc_tomcat']['loglevel'] = 'INFO'
default['hc_tomcat']['tomcat_auth'] = 'true'
default['hc_tomcat']['client_auth'] = 'false'
default['hc_tomcat']['instances'] = {}
default['hc_tomcat']['run_base_instance'] = true
default['hc_tomcat']['environment'] = []
default['hc_tomcat']['packages'] = ["tomcat#{node['hc_tomcat']['base_version']}"]
default['hc_tomcat']['deploy_manager_packages'] = ["tomcat#{node['hc_tomcat']['base_version']}-admin"]
default['hc_tomcat']['ajp_packetsize'] = '8192'
default['hc_tomcat']['uriencoding'] = 'UTF-8'
case node['platform_family']

when 'rhel', 'debian', 'ubuntu'
  #suffix = node['hc_tomcat']['base_version'].to_i < 7 ? node['hc_tomcat']['base_version'] : ''
  suffix = node['hc_tomcat']['base_version']

  default['hc_tomcat']['base_instance'] = "tomcat#{suffix}"
  default['hc_tomcat']['user'] = 'tomcat'
  default['hc_tomcat']['group'] = 'tomcat'
  #default['hc_tomcat']['home'] = "#{node['hc_tomcat']['tomcat_home']}#{suffix}"
  #default['hc_tomcat']['base'] = "#{node['hc_tomcat']['tomcat_home']}#{suffix}"
  default['hc_tomcat']['home'] = node['hc_tomcat']['tomcat_home']
  default['hc_tomcat']['base'] = node['hc_tomcat']['tomcat_home']
  #default['hc_tomcat']['config_dir'] = "/etc/tomcat#{suffix}"
  default['hc_tomcat']['config_dir'] = '/etc/tomcat'
  default['hc_tomcat']['source_dir'] = "#{node['product']}"
  if node.attribute?(:implementation)
    default['hc_tomcat']['source_dir'] = "#{node['product']}/#{node['implementation']}"
  end
  default['hc_tomcat']['log_dir'] = "/var/log/tomcat#{suffix}"
  default['hc_tomcat']['scimweblogs_dir'] = '/opt/idm/scimweb_logs'

  default['hc_tomcat']['tmp_dir'] = "/var/cache/tomcat#{suffix}/temp"
  default['hc_tomcat']['work_dir'] = "/var/cache/tomcat#{suffix}/work"
  default['hc_tomcat']['context_dir'] = "#{node['hc_tomcat']['config_dir']}/Catalina/localhost"
  default['hc_tomcat']['webapp_dir'] = "#{node['hc_tomcat']['tomcat_home']}/webapps"
  #default['hc_tomcat']['keytool'] = 'keytool'
  default['hc_tomcat']['keytool'] = "#{node['hc_java']['java_home']}/jre/bin/keytool"
  default['hc_tomcat']['lib_dir'] = "#{node['hc_tomcat']['home']}/lib"
  default['hc_tomcat']['endorsed_dir'] = "#{node['hc_tomcat']['lib_dir']}/endorsed"
  default['hc_tomcat']['packages'] = ["tomcat#{suffix}"]
  default['hc_tomcat']['deploy_manager_packages'] = ["tomcat#{suffix}-admin-webapps"]
  default['hc_tomcat']['log_path'] = '/var/log'
  default['hc_tomcat']['ojdbc_jars'] = ['ojdbc14-10.2.0.3.0.jar', 'ojdbc6.jar']
  default['hc_tomcat']['lib_home'] = '/usr/local/tomcat/lib'
else
  default['hc_tomcat']['user'] = "tomcat#{node['hc_tomcat']['base_version']}"
  default['hc_tomcat']['group'] = "tomcat#{node['hc_tomcat']['base_version']}"
  default['hc_tomcat']['home'] = "/usr/share/tomcat#{node['hc_tomcat']['base_version']}"
  default['hc_tomcat']['base'] = "/var/lib/tomcat#{node['hc_tomcat']['base_version']}"
  default['hc_tomcat']['config_dir'] = "/etc/tomcat#{node['hc_tomcat']['base_version']}"
  default['hc_tomcat']['log_dir'] = "/var/log/tomcat#{node['hc_tomcat']['base_version']}"
  default['hc_tomcat']['tmp_dir'] = "/tmp/tomcat#{node['hc_tomcat']['base_version']}-tmp"
  default['hc_tomcat']['work_dir'] = "/var/cache/tomcat#{node['hc_tomcat']['base_version']}"
  default['hc_tomcat']['context_dir'] = "#{node['hc_tomcat']['config_dir']}/Catalina/localhost"
  default['hc_tomcat']['webapp_dir'] = "/var/lib/tomcat#{node['hc_tomcat']['base_version']}/webapps"
  default['hc_tomcat']['keytool'] = 'keytool'
  default['hc_tomcat']['lib_dir'] = "#{node['hc_tomcat']['home']}/lib"
  default['hc_tomcat']['endorsed_dir'] = "#{node['hc_tomcat']['lib_dir']}/endorsed"
  default['hc_tomcat']['ojdbc_jars'] = ['ojdbc14-10.2.0.3.0.jar', 'ojdbc6.jar']
  default['hc_tomcat']['lib_home'] = '/usr/local/tomcat/lib'
end

#Properties to be populated in setenv.sh
default['hc_tomcat']['idm']['app_prop'] = '/opt/idm/resources/application.properties'
default['hc_tomcat']['idm']['app_config_prop'] = '/opt/idm/resources/appConfig.properties'
default['hc_tomcat']['idm']['idp_app_tenant_prop'] = '/opt/idm/resources/idpAppTenant.properties'
default['hc_tomcat']['idm']['log4j_prop'] = '/opt/idm/resources/log4j.properties'
#Adding as per JIRA-35990
default['hc_tomcat']['sso']['scimweblogs_dir'] = '/var/log/sso/scimweb_logs'
default['hc_tomcat']['sso']['idm']['log4j_prop'] = "#{node['hc_tomcat']['tomcat_home']}/logback/logback.properties"
default['hc_tomcat']['idm']['resources_path'] = '/opt/idm/resources'
default['hc_tomcat']['idm']['zendesk_app_prop'] = '/opt/idm/resources/zendesk-application.properties'

#CP PHIX APP Specific properties

default['hc_tomcat']['phix']['cp']['app']['opts']['headless'] = 'true'
default['hc_tomcat']['phix']['cp']['app']['opts']['xms'] = '14G'
#default['hc_tomcat']['phix']['cp']['app']['opts']['xmx'] = '14G'
default['hc_tomcat']['phix']['cp']['app']['opts']['newsize'] = '1536m'
default['hc_tomcat']['phix']['cp']['app']['opts']['max_newsize'] = '2560m'
default['hc_tomcat']['phix']['cp']['app']['opts']['maxtenuringthreshold'] = '15'
default['hc_tomcat']['phix']['cp']['app']['opts']['permsize'] = '1024m'
default['hc_tomcat']['phix']['cp']['app']['opts']['maxpermsize'] = '1024m'
default['hc_tomcat']['phix']['cp']['app']['opts']['reservedcodecachesize'] = '240m'
default['hc_tomcat']['phix']['cp']['app']['opts']['xloggc'] = ''
default['hc_tomcat']['phix']['cp']['app']['opts']['initiatingheapoccupancypercent'] = '80'
default['hc_tomcat']['phix']['cp']['app']['opts']['heapdumppath'] = '/var/log/phix/heapdump'
default['hc_tomcat']['phix']['cp']['app']['opts']['xmx_percentage'] = '60'
default['hc_tomcat']['phix']['cp']['app']['opts']['metaspacesize'] = '1024m'

#CP PHIX BATCH Specific properties
default['hc_tomcat']['phix']['cp']['batch']['opts']['headless'] = 'true'
default['hc_tomcat']['phix']['cp']['batch']['opts']['xms'] = '5120m'
#default['hc_tomcat']['phix']['cp']['batch']['opts']['xmx'] = '5120m'
default['hc_tomcat']['phix']['cp']['batch']['opts']['newsize'] = '1536m'
default['hc_tomcat']['phix']['cp']['batch']['opts']['max_newsize'] = '2560m'
default['hc_tomcat']['phix']['cp']['batch']['opts']['maxpermsize'] = '1024m'
default['hc_tomcat']['phix']['cp']['batch']['opts']['initiatingheapoccupancypercent'] = '80'
default['hc_tomcat']['phix']['cp']['batch']['opts']['xmx_percentage'] = '60'
#fidelity PHIX APP Specific properties
default['hc_tomcat']['phix']['fidelity']['app']['opts']['headless'] = 'true'
default['hc_tomcat']['phix']['fidelity']['app']['opts']['xms'] = '11G'
#default['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx'] = '11G'
default['hc_tomcat']['phix']['fidelity']['app']['opts']['maxtenuringthreshold'] = '20'
default['hc_tomcat']['phix']['fidelity']['app']['opts']['permsize'] = '1024m'
default['hc_tomcat']['phix']['fidelity']['app']['opts']['maxpermsize'] = '1024m'
default['hc_tomcat']['phix']['fidelity']['app']['opts']['reservedcodecachesize'] = '240m'
default['hc_tomcat']['phix']['fidelity']['app']['opts']['initiatingheapoccupancypercent'] = '60'
default['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx_percentage'] = '60'
default['hc_tomcat']['phix']['fidelity']['app']['opts']['maxgcpausemillis'] = '600'

#fidelity PHIX BATCH Specific properties
default['hc_tomcat']['phix']['fidelity']['batch']['opts']['headless'] = 'true'
default['hc_tomcat']['phix']['fidelity']['batch']['opts']['xms'] = '5120m'
#default['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx'] = '5120m'
default['hc_tomcat']['phix']['fidelity']['batch']['opts']['newsize'] = '1536m'
default['hc_tomcat']['phix']['fidelity']['batch']['opts']['max_newsize'] = '2560m'
default['hc_tomcat']['phix']['fidelity']['batch']['opts']['maxpermsize'] = '1024m'
default['hc_tomcat']['phix']['fidelity']['batch']['opts']['initiatingheapoccupancypercent'] = '80'
default['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx_percentage'] = '60'

#wellcare PHIX APP Specific properties
default['hc_tomcat']['phix']['wellcare']['app']['opts']['headless'] = 'true'
default['hc_tomcat']['phix']['wellcare']['app']['opts']['xms'] = '11G'
#default['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx'] = '11G'
default['hc_tomcat']['phix']['wellcare']['app']['opts']['maxtenuringthreshold'] = '20'
default['hc_tomcat']['phix']['wellcare']['app']['opts']['permsize'] = '1024m'
default['hc_tomcat']['phix']['wellcare']['app']['opts']['maxpermsize'] = '1024m'
default['hc_tomcat']['phix']['wellcare']['app']['opts']['reservedcodecachesize'] = '240m'
default['hc_tomcat']['phix']['wellcare']['app']['opts']['initiatingheapoccupancypercent'] = '60'
default['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx_percentage'] = '60'
default['hc_tomcat']['phix']['wellcare']['app']['opts']['maxgcpausemillis'] = '600'

#wellcare PHIX BATCH Specific properties
default['hc_tomcat']['phix']['wellcare']['batch']['opts']['headless'] = 'true'
default['hc_tomcat']['phix']['wellcare']['batch']['opts']['xms'] = '5120m'
#default['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx'] = '5120m'
default['hc_tomcat']['phix']['wellcare']['batch']['opts']['newsize'] = '1536m'
default['hc_tomcat']['phix']['wellcare']['batch']['opts']['max_newsize'] = '2560m'
default['hc_tomcat']['phix']['wellcare']['batch']['opts']['maxpermsize'] = '1024m'
default['hc_tomcat']['phix']['wellcare']['batch']['opts']['initiatingheapoccupancypercent'] = '80'
default['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx_percentage'] = '60'

if node[:hc_tomcat][:phix][:wellcare].attribute?(:batch)
  if node[:hc_tomcat][:phix][:wellcare][:batch]['opts'].attribute?(:xmx)
    default['hc_tomcat']['phix']['wellcare']['batch']['opts']['xms'] = node['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx']
  else
    default['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx'] = (node['memory']['total'][0..-3].to_f / 1024) * (node['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx_percentage'].to_f / 100)
    default['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx'] = "#{node['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx'].to_i}M"
    default['hc_tomcat']['phix']['wellcare']['batch']['opts']['xms'] = node['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx']
  end
default['hc_tomcat']['phix']['wellcare']['batch']['java_opts'] = "-Djava.awt.headless=true -Xmx#{node['hc_tomcat']['phix']['wellcare']['batch']['opts']['xmx']} -Xms#{node['hc_tomcat']['phix']['wellcare']['batch']['opts']['xms']} -XX:MaxPermSize=#{node['hc_tomcat']['phix']['wellcare']['batch']['opts']['maxpermsize']} -XX:NewSize=#{node['hc_tomcat']['phix']['wellcare']['batch']['opts']['newsize']} -XX:MaxNewSize=#{node['hc_tomcat']['phix']['wellcare']['batch']['opts']['max_newsize']} -XX:InitiatingHeapOccupancyPercent=#{node['hc_tomcat']['phix']['wellcare']['batch']['opts']['initiatingheapoccupancypercent']}"
end
if node[:hc_tomcat][:phix][:wellcare][:app][:opts].attribute?(:xmx)
  default['hc_tomcat']['phix']['wellcare']['app']['opts']['xms'] = node['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx']
else
  default['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx'] = (node['memory']['total'][0..-3].to_f / 1024) * (node['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx_percentage'].to_f / 100)
  default['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx'] = "#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx'].to_i}M"
  default['hc_tomcat']['phix']['wellcare']['app']['opts']['xms'] = node['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx']
end

default['hc_tomcat']['phix']['wellcare']['app']['java_opts'] = "-Djava.awt.headless=#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['headless']} -server -XX:+UseCompressedOops -Xms#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['xms']} -Xmx#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['xmx']} -XX:MaxTenuringThreshold=#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['maxtenuringthreshold']} -XX:PermSize=#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['permsize']} -XX:MaxPermSize=#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['maxpermsize']}   -XX:+UseCompressedOops -XX:ReservedCodeCacheSize=#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['reservedcodecachesize']} -XX:+UseG1GC -XX:MaxGCPauseMillis=#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['maxgcpausemillis']} -XX:InitiatingHeapOccupancyPercent=#{node['hc_tomcat']['phix']['wellcare']['app']['opts']['initiatingheapoccupancypercent']} -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled"


if node[:hc_tomcat][:phix][:cp][:app][:opts].attribute?(:xmx)
  default['hc_tomcat']['phix']['cp']['app']['opts']['xms'] = node['hc_tomcat']['phix']['cp']['app']['opts']['xmx']
else
  default['hc_tomcat']['phix']['cp']['app']['opts']['xmx'] = (node['memory']['total'][0..-3].to_f / 1024) * (node['hc_tomcat']['phix']['cp']['app']['opts']['xmx_percentage'].to_f / 100)
  default['hc_tomcat']['phix']['cp']['app']['opts']['xmx'] = "#{node['hc_tomcat']['phix']['cp']['app']['opts']['xmx'].to_i}M"
  default['hc_tomcat']['phix']['cp']['app']['opts']['xms'] = node['hc_tomcat']['phix']['cp']['app']['opts']['xmx']
end

#default['hc_tomcat']['phix']['cp']['app']['java_opts'] = "-Djava.awt.headless=#{node['hc_tomcat']['phix']['cp']['app']['opts']['headless']} -server -Xms#{node['hc_tomcat']['phix']['cp']['app']['opts']['xms']} -Xmx#{node['hc_tomcat']['phix']['cp']['app']['opts']['xmx']} -XX:NewSize=#{node['hc_tomcat']['phix']['cp']['app']['opts']['newsize']} -XX:MaxNewSize=#{node['hc_tomcat']['phix']['cp']['app']['opts']['max_newsize']} -XX:MaxTenuringThreshold=#{node['hc_tomcat']['phix']['cp']['app']['opts']['maxtenuringthreshold']} -XX:PermSize=#{node['hc_tomcat']['phix']['cp']['app']['opts']['permsize']} -XX:MaxPermSize=#{node['hc_tomcat']['phix']['cp']['app']['opts']['maxpermsize']} -XX:+UseCompressedOops -XX:ReservedCodeCacheSize=#{node['hc_tomcat']['phix']['cp']['app']['opts']['reservedcodecachesize']} -XX:+UseG1GC -Xloggc:#{node['hc_tomcat']['phix']['cp']['app']['opts']['xloggc']} -XX:+PrintGCDetails -XX:InitiatingHeapOccupancyPercent=#{node['hc_tomcat']['phix']['cp']['app']['opts']['initiatingheapoccupancypercent']} -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=#{node['hc_tomcat']['phix']['cp']['app']['opts']['heapdumppath']}"
default['hc_tomcat']['phix']['cp']['app']['java_opts'] = "$JAVA_OPTS -Djava.awt.headless=#{node['hc_tomcat']['phix']['cp']['app']['opts']['headless']} -server -Xms#{node['hc_tomcat']['phix']['cp']['app']['opts']['xms']} -Xmx#{node['hc_tomcat']['phix']['cp']['app']['opts']['xmx']} -Xloggc:/var/log/phix/javagc_`date '+%y%m%d_%H%M%S'`.log -XX:+PrintGCDetails -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=#{node['hc_tomcat']['phix']['cp']['app']['opts']['heapdumppath']} -XX:+UseCompressedOops -XX:+UseG1GC"

if node[:hc_tomcat][:phix][:cp].attribute?(:batch)
  if node[:hc_tomcat][:phix][:cp][:batch]['opts'].attribute?(:xmx)
    default['hc_tomcat']['phix']['cp']['batch']['opts']['xms'] = node['hc_tomcat']['phix']['cp']['batch']['opts']['xmx']
  else
    default['hc_tomcat']['phix']['cp']['batch']['opts']['xmx'] = (node['memory']['total'][0..-3].to_f / 1024) * (node['hc_tomcat']['phix']['cp']['batch']['opts']['xmx_percentage'].to_f / 100)
    default['hc_tomcat']['phix']['cp']['batch']['opts']['xmx'] = "#{node['hc_tomcat']['phix']['cp']['batch']['opts']['xmx'].to_i}M"
    default['hc_tomcat']['phix']['cp']['batch']['opts']['xms'] = node['hc_tomcat']['phix']['cp']['batch']['opts']['xmx']
  end

  #default['hc_tomcat']['phix']['cp']['batch']['java_opts'] = "-Djava.awt.headless=true -Xmx#{node['hc_tomcat']['phix']['cp']['batch']['opts']['xmx']} -Xms#{node['hc_tomcat']['phix']['cp']['batch']['opts']['xms']} -XX:MaxPermSize=#{node['hc_tomcat']['phix']['cp']['batch']['opts']['maxpermsize']} -XX:NewSize=#{node['hc_tomcat']['phix']['cp']['batch']['opts']['newsize']} -XX:MaxNewSize=#{node['hc_tomcat']['phix']['cp']['batch']['opts']['max_newsize']} -XX:InitiatingHeapOccupancyPercent=#{node['hc_tomcat']['phix']['cp']['batch']['opts']['initiatingheapoccupancypercent']}"
  default['hc_tomcat']['phix']['cp']['batch']['java_opts'] = "$JAVA_OPTS -Xmx#{node['hc_tomcat']['phix']['cp']['batch']['opts']['xmx']} -Xms#{node['hc_tomcat']['phix']['cp']['batch']['opts']['xms']} -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=#{node['hc_tomcat']['phix']['cp']['app']['opts']['heapdumppath']}"

end

if node[:hc_tomcat][:phix][:fidelity][:app][:opts].attribute?(:xmx)
  default['hc_tomcat']['phix']['fidelity']['app']['opts']['xms'] = node['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx']
else
  default['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx'] = (node['memory']['total'][0..-3].to_f / 1024) * (node['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx_percentage'].to_f / 100)
  default['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx'] = "#{node['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx'].to_i}M"
  default['hc_tomcat']['phix']['fidelity']['app']['opts']['xms'] = node['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx']
end

if node[:hc_tomcat][:phix][:fidelity].attribute?(:batch)
  if node[:hc_tomcat][:phix][:fidelity][:batch]['opts'].attribute?(:xmx)
    default['hc_tomcat']['phix']['fidelity']['batch']['opts']['xms'] = node['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx']
  else
    default['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx'] = (node['memory']['total'][0..-3].to_f / 1024) * (node['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx_percentage'].to_f / 100)
    default['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx'] = "#{node['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx'].to_i}M"
    default['hc_tomcat']['phix']['fidelity']['batch']['opts']['xms'] = node['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx']
  end
default['hc_tomcat']['phix']['fidelity']['batch']['java_opts'] = "-Djava.awt.headless=true -Xmx#{node['hc_tomcat']['phix']['fidelity']['batch']['opts']['xmx']} -Xms#{node['hc_tomcat']['phix']['fidelity']['batch']['opts']['xms']} -XX:MaxPermSize=#{node['hc_tomcat']['phix']['fidelity']['batch']['opts']['maxpermsize']} -XX:NewSize=#{node['hc_tomcat']['phix']['fidelity']['batch']['opts']['newsize']} -XX:MaxNewSize=#{node['hc_tomcat']['phix']['fidelity']['batch']['opts']['max_newsize']} -XX:InitiatingHeapOccupancyPercent=#{node['hc_tomcat']['phix']['fidelity']['batch']['opts']['initiatingheapoccupancypercent']}"
end
default['hc_tomcat']['phix']['fidelity']['app']['java_opts'] = "-Djava.awt.headless=#{node['hc_tomcat']['phix']['fidelity']['app']['opts']['headless']} -server -Xms#{node['hc_tomcat']['phix']['fidelity']['app']['opts']['xms']} -Xmx#{node['hc_tomcat']['phix']['fidelity']['app']['opts']['xmx']} -XX:+UseCompressedOops -XX:+UseG1GC -XX:+PrintGCDetails -XX:+DisableExplicitGC -Xloggc:/var/log/phix/javagc_`date '+%y%m%d_%H%M%S'`.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/phix/heapdump"

<<'COMMENT'
#Testing chef-sugar for more sweetness!!!
namespace 'hc_tomcat', 'phix', 'cp', 'batch', 'opts' do
  headless 'true'
  xms '14G'
  xmx '14G'd
  newsize '1536m'
  max_newsize '2560m'
  maxpermsize '1024m'
  initiatingheapoccupancypercent '80'
  xmx_percentage '60'
end
COMMENT
default['hc_tomcat']['sso']['opts']['xms'] = '2048m'
#default['hc_tomcat']['sso']['opts']['xmx'] = '2048m'
default['hc_tomcat']['sso']['opts']['xmsx_percentage'] = '60'
default['hc_tomcat']['sso']['opts']['permsize'] = '128M'
default['hc_tomcat']['sso']['opts']['maxpermsize'] = '512M'

if node[:hc_tomcat][:sso][:opts].attribute?(:xmx)
  default['hc_tomcat']['sso']['opts']['xms'] = node['hc_tomcat']['sso']['opts']['xmx']
else
  default['hc_tomcat']['sso']['opts']['xmx'] = (node['memory']['total'][0..-3].to_f / 1024) * (node['hc_tomcat']['sso']['opts']['xmsx_percentage'].to_f / 100)
  default['hc_tomcat']['sso']['opts']['xmx'] = "#{node['hc_tomcat']['sso']['opts']['xmx'].to_i}M"
  default['hc_tomcat']['sso']['opts']['xms'] = node['hc_tomcat']['sso']['opts']['xmx']
end
